### ISSUE TITLE
Provide flakes support?

### ISSUE THREAD

**Issue by dit7ya** [arcnmx/nixexprs#38]
Thanks for writing these! It would be awesome to use these in flake enabled configuration - so some instructions on how to achieve that in the Readme will be super helpful.

**Comment by arcnmx** [comment]
Yeah I should get around to this, I kind of put it off due to #24 and then got sidetracked...

In the meantime, you should be able to use it like any other non-flake input:
```nix
{
  inputs.nixpkgs.url = "nixpkgs";
  inputs.arc = {
    url = "github:arcnmx/nixexprs";
    flake = false;
  };
  outputs = { nixpkgs, arc, self }: (import arc { pkgs = nixpkgs.${system}.legacyPackages; }).blah;
}
```
